[package]
name = "karaagecc_source"
version = "0.1.0"
edition = "2021"

[dependencies]
nanoid = "0.4.0"
karaagecc_chars = { path = "../karaagecc_chars" }

[dev-dependencies]
karaage_asserts = { path = "../karaage_asserts" }
