[workspace]
members = [
  "karaagecc_cli",
  "karaagecc",
  "karaagecc_chars",
  "karaagecc_error",
  "karaagecc_source",
  "karaagecc_token",
  "karaagecc_ast",
  "karaagecc_lexer",
  "karaageir",
  "karaageir_codegen",
  "karaage_asserts",
]
