[package]
name = "karaagecc_token"
version = "0.1.0"
edition = "2021"

[dependencies]
karaagecc_source = { path = "../karaagecc_source" }
karaage_utils = { path = "../karaage_utils" }

[dev-dependencies]
karaage_asserts = { path = "../karaage_asserts" }
