[package]
name = "karaagecc_cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "karaagecc"
path = "src/main.rs"

[dependencies]
clap = { version = "3", features = ["derive"] }
karaagecc = { path = "../karaagecc" }
